spring.application.name=api-gateway
server.port=${SERVER_PORT:8765}

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

# Quiz Service Route
spring.cloud.gateway.routes[0].id=quiz-service
spring.cloud.gateway.routes[0].uri=lb://quiz-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
